title: Praneet Bachheti
description: Senior Principal Engineer in Fremont. Networking and security systems, patents, violin, and the outdoors.
url: https://praneetb.github.io
baseurl: ""

markdown: kramdown
permalink: pretty
theme: null

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor
  - config
  - CNAME
  - cover
  - scripts
